### ISSUE TITLE
Federation relay?

### ISSUE THREAD

**Issue by bitboxer** [awooo-club/awooo.club#1]
Do we want to enable federation relay to fill up the local timeline?

https://github.com/tootsuite/mastodon/pull/7998

**Comment by bitboxer** [comment]
db size: 2018-10-27 16:00 local time: 531 MB

Disk size of the image volume: 14gig

Should we close this now?

**Comment by gildesmarais** [comment]
Closing, and we need to focus on #4 more now. :)
