### ISSUE TITLE
Monitoring of the application and server

### ISSUE THREAD

**Issue by gildesmarais** [awooo-club/awooo.club#4]
We need to monitor that the instance is working as intended ;)

Should we have health-checks for the application and monitor the server (IMHO it's important to monitor, since the small hetzner cloud server is quite limited in its resources)?

1. For simple application monitoring via HTTPs, there's uptimerobot.com with a free plan, which allows plents of checks every 5 minutes.
2. For cronjobs, we could use healthchecks.io to monitor that they're being executed successfully
3. should we setup a sentry or similar service to monitor the application?

**Comment by gildesmarais** [comment]
i've installed telegraf and set up some alerts on my personal Kapacitor for awooo.club:

![image](https://user-images.githubusercontent.com/350021/54492723-42ed8700-48c9-11e9-97c0-5a2aa8639929.png)

I'll let those 3 basic checks run for a while to get a feel for their noisiness. Then I'll add adjust and finally add your email address to the recipients. Oh and of course a deadman switch, when no data is coming in, will be set up. 
If you think we should monitor more than that, just ping me and we can configure those. :)

**Comment by bitboxer** [comment]
👍

**Comment by gildesmarais** [comment]
@bitboxer I've added your uptime email address into the recipients list.

In the last week zero alarms were triggered, the machine barely has any load, except using sometimes up to ~70% of its available memory (which does not trigger any alarm).

**Comment by bitboxer** [comment]
We could raise the memory by upgrading to the next bigger server. That would only help during deploy right now because i need to stop the server to build the assets right now. So this would be the only downtime alarm for us. But i can live with doing that right now. So for me i think we can live with that till mastodon starts using more memory.

**Comment by gildesmarais** [comment]
Since this instance is not critical infrastructure, I'm also totally fine with it being down for a short amount of time during an upgrade. We should start thinking about upgrading the host as soon as the 'memory usage' alarms start to annoy us ;)
