### ISSUE TITLE
Instance Thumbnail and Hero Image

### ISSUE THREAD

**Issue by bitboxer** [awooo-club/awooo.club#5]
We should make our instance a bit more beautiful 🖼

**Comment by gildesmarais** [comment]
some suggestion, in no particular order, numbered for easy reference:

1. https://pixabay.com/en/mammoth-park-tusks-proboscis-1127772/
2. https://unsplash.com/photos/sJQTvXc7mNY
3. https://unsplash.com/photos/OP3ghv27Yto
4. https://unsplash.com/photos/50cwlQ56UCY
5. https://unsplash.com/photos/jemWdDSvgd0
6. https://unsplash.com/photos/H3U_HA1arI4
7. https://unsplash.com/photos/BuQ1RZckYW4

**Comment by gildesmarais** [comment]
cropped and uploaded it. see it at: https://awooo.club/about

now, for the hero and mascot: what do we want there? :)

**Comment by gildesmarais** [comment]
took the liberty to change the mascot to this: https://unsplash.com/photos/4lbx1NdUa0s
same photographer, so maybe it's the same animal as seen in the thumbnail.

are you ok with that? should i upload the pixelmator file?

**Comment by bitboxer** [comment]
Looks good to me. Should we close this now? And feel free to upload the file to this repo if you want.
